AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SayHello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sayhello.handler.handler
      Runtime: python3.7
      Timeout: 60
      Policies: AWSLambdaExecute
